dist: trusty

language: node_js
node_js:
  - "node"

services: docker

install:
  - docker build -t nodedock .
  - docker run -d -e PORT=3001 -p 3001:3001 --name nodedock nodedock

before_script:
  - yarn install

script:
  - docker ps | grep -q nodedock
  - yarn run test
