dist: trusty

language: node_js
node_js:
  - "node"

services: docker

install:
  - docker build -t nodedock .
  - docker run -d -e PORT=80 -p 127.0.0.1:80:3001 --name nodedock nodedock

script:
  - docker ps | grep -q nodedock
  - yarn run test
